spring:
#  data.mongodb.uri: mongodb://localhost:27018
  data.mongodb.uri: mongodb://47.106.221.253:27018
  data.mongodb.database: test


logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG

server:
  port: 8081










